version: '2'
services:
  buildbot:
    image: buildbot/buildbot-master:master
    env_file:
        - db.env
    environment:
        - BUILDBOT_CONFIG_DIR=config
        - BUILDBOT_CONFIG_URL=https://github.com/Nordgedanken/buildbot-riot-web/archive/master.tar.gz
        - BUILDBOT_WORKER_PORT=9989
        - BUILDBOT_WEB_URL=http://riot.nordgedanken.de:8080/
        - BUILDBOT_WEB_PORT=8080
        - VIRTUAL_HOST=riot.nordgedanken.de
        - VIRTUAL_PORT=8080
        - LETSENCRYPT_HOST=riot.nordgedanken.de
        - LETSENCRYPT_EMAIL=info@nordgedanken.de
    links:
      - db
    depends_on:
      - db
    expose:
      - 8080
    network_mode: "bridge"
  db:
    env_file:
        - db.env
    image: "postgres:9.4"
    expose:
        - 5432
    network_mode: "bridge"

  worker:
    image: "buildbot/buildbot-worker:master"
    environment:
        BUILDMASTER: buildbot
        BUILDMASTER_PORT: 9989
        WORKERNAME: example-worker
        WORKERPASS: pass
        WORKER_ENVIRONMENT_BLACKLIST: DOCKER_BUILDBOT* BUILDBOT_ENV_* BUILDBOT_1* WORKER_ENVIRONMENT_BLACKLIST

    links:
        - buildbot
    network_mode: "bridge"
